logging:
  level:
    com.github.lucbui.fracktail3: DEBUG

management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
    scheduledtasks:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics,scheduledtasks

discord:
  prefix: '?'
  status:
    presence: DO_NOT_DISTURB
    activity: PLAYING
    string: i'm a baby fracktail

twitch:
  prefix: '?'