logging:
  level:
    com.github.lucbui.fracktail3: DEBUG

management:
  endpoint:
    health:
      show-details: always

discord:
  prefix: '?'
  status:
    presence: DO_NOT_DISTURB
    activity: PLAYING
    string: i'm a baby fracktail